<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.8.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelioHub.Notification.BLL.Logic\HelioHub.Notification.BLL.Logic.csproj" />
    <ProjectReference Include="..\HelioHub.Notification.Contracts\HelioHub.Notification.Contracts.csproj" />
    <ProjectReference Include="..\HelioHub.Notification.Entities\HelioHub.Notification.Entities.csproj" />
  </ItemGroup>

</Project>
